### ISSUE TITLE
Migrate from SDL2 to GLFW.

### ISSUE THREAD

**Issue by RubyNova** [novelrt/NovelRT#105]
As per #104 and #106 , SDL2 is breaking in multiple places that are completely unexpected, at least on windows.

It appears modern GLFW may work better for our needs.

This means replacing things such as sdl_image with libpng, but I don't personally mind that as one of the main developers working on the graphics pipelines. It also has better support for Vulkan OOTB, it seems, unlike SDL2.

I am very much for this, given the duct tape in #98 to get around one of these issues.

**Comment by capnkenny** [comment]
One area of concern is Mobile development, primarily iOS. Seeing as that we don't have anyone truly experienced in iOS development ATM, we may need to research this for alternatives - however due to the recent Apple ecosystem changes, I think we are safe to say this shouldn't be a blocker for us.

As far as Android is comcerned, @RubyNova mentioned having a plan for NDK/native support.

**Comment by RubyNova** [comment]
For what its worth, even if we don't decide to use GLFW, SDL2 is clearly giving us build problems amongst other issues. I'm pretty concerned we'll just end up fighting the library more and more as time goes on.

**Comment by RubyNova** [comment]
Just a quick update on this ticket - after talking with @tannergooding on discord, the previously mentioned wontfix issue with the window resizing has actually now been resolved. This was a mistake on my part for, I guess, failing to google the right things as I was only ever shown the event we were using originally. My bad.

**Comment by tannergooding** [comment]
Something I noticed with SDL2 is that what subsystems it uses depends on what was available on box when you compiled and that it will compile even if no "base" exists.

So, for example, if you compile SDL2 and `libx11-dev` is installed, it will use `X11` when creating the Window and won't work with wayland or xcb. This can lead to surprise failures at runtime as it won't be able to find a valid video or audio device.

We should check the behavior of glfw and see if it is any better here. It would be nice if there was some dynamic binding support (like you would get in C#) where it can try a range of backends and pick whichever works.
