### ISSUE TITLE
SDL2 Does not compile to WebGL.

### ISSUE THREAD

**Issue by RubyNova** [novelrt/NovelRT#106]
As per an internal discussion on discord with myself and @capnkenny , SDL2 simply isn't playing ball with our WebGL/WASM build despite SDL2 specifying it is WebGL and WASM compliant.

This isn't something we can fix, without just gutting SDL2. See #105 for the proposal on this.

As a result, we are not fixing this if the proposal does not go through (it most probably should, but I am not about to put words into other developers' mouths).

**Comment by capnkenny** [comment]
To clarify, we have a desire to target WebGL2/ES 3.0 as our rendering API, which although it was "fixed" supposedly by SDL2, it _refuses_ to target correctly in an Emscripten build. However, multiple tests using Regal, GLFW, and just native GL code to create an ES 3.0 context appear to work OOTB with minimal configuration and changes to the shaders we currently have.

**Comment by capnkenny** [comment]
SDL2 is no longer a dependency - closing.
