### ISSUE TITLE
AzDO CI is using GCC for Ubuntu.

### ISSUE THREAD

**Issue by RubyNova** [novelrt/NovelRT#109]
This is something I noticed in one of our most recent logs, specifically in PR #54 . You can see the line here: https://dev.azure.com/NovelRT/NovelRT/_build/results?buildId=252&view=logs&j=3c3857a6-1d57-5b95-59be-23dc93fab9b7&t=b1a888d4-fc2f-5b54-84b8-f0547cafd7d8&l=40

I'm guessing this is just a flag we missed? It's supposed to register as `Clang++`.

**Comment by tannergooding** [comment]
The `g++-8` usage here looks to be for the vcpkg build. The `novelrt` build is being done with `clang`

**Comment by tannergooding** [comment]
It looks like its because they explicitly override to use `g++` here:https://github.com/microsoft/vcpkg/blob/master/scripts/bootstrap.sh#L200

**Comment by RubyNova** [comment]
Hmm, that's a bit weird. Do we just want to accept this as the default behaviour?

Is it possible clang might fall over at some point by mixing compilers like this?

**Comment by tannergooding** [comment]
> Hmm, that's a bit weird.

Not really any more so than us referencing clang by default ;)

> Do we just want to accept this as the default behaviour?

It looks like we might be able to override to clang, but I'd have to go through their build script more in depth to be sure.

> Is it possible clang might fall over at some point by mixing compilers like this?

It shouldn't be a problem. We still build with clang like we intend to and clang and gcc are required to output binary compatible object files on Unix (which defines the elf file format, a standard calling convention and standard runtime abi).

**Comment by tannergooding** [comment]
Also, to maybe clarify, it looks like only the vcpkg executable that builds with gcc.

The "ports" (like sdl, nethost, freestyle, etc) are all built separately via cmake and look to use the system default (which we set to clang).

**Comment by RubyNova** [comment]
I see - yeah I guess us using clang is "non standard", though I'm choosing to use it to make our leap to mac easier. Though if you think its not an issue we could just leave it be if you think that's safest?

**Comment by tannergooding** [comment]
Yeah, I think leaving other repos using their preferred compiler is the safest choice; so I'll close this bug for now. We would likely need to open a bug against vcpkg to support clang by default if we wanted something else.
