### ISSUE TITLE
Research: JS bindings

### ISSUE THREAD

**Issue by capnkenny** [novelrt/NovelRT#113]
Currently, we've received some feedback for JS/Node support, however this has not been _fully_ looked into.

At the moment, the following research needs to be done:

- Emscripten viability [ ]
- V8 Engine viability [ ]
- Other methods of calling C++ from JS

This will also be driven by community feedback, to help gauge interest and steer research into the right area.
However, we still have other milestones to hit, so this will be done in the background.

**Comment by capnkenny** [comment]
Assigned to myself as I have already been playing with emscripten support and web api porting

**Comment by jmazouri** [comment]
Perhaps consider looking into a binding library like https://github.com/pmed/v8pp which can help bridge the gap between the existing c++ API and V8

**Comment by capnkenny** [comment]
Unassigning as I have too much to do already - if anyone's interested in continuing research during/after C API development it's up for grabs 😄

**Comment by capnkenny** [comment]
We have decided that we will not be pursuing JS bindings for the foreseeable future, and as such this is being closed.

When the time is right, we shall be reviewing implementations for _exporting_ projects via WASM (Mono/Rust WASM, Emscripten, etc), but now is not the right time.
