### ISSUE TITLE
Freetype now requires Harfbuzz explicitly due to vcpkg bug.

### ISSUE THREAD

**Issue by RubyNova** [novelrt/NovelRT#127]
Due to https://github.com/microsoft/vcpkg/issues/10041 we require Harfbuzz as an explicit dependency for the time being. This can't be fixed until vcpkg resolves its own issue first.

**Comment by capnkenny** [comment]
We should most likely continue to use NovelRT's fork of vcpkg for the tine being, but this has been resolved by MSFT and can be closed.

**Comment by RubyNova** [comment]
closing then.
