### ISSUE TITLE
Basic Audio Implementation

### ISSUE THREAD

**Issue by capnkenny** [novelrt/NovelRT#13]
[AB#2](https://dev.azure.com/NovelRT/16e5528b-8bb4-4e2b-b064-e26926458e42/_workitems/edit/2)

Requirements for a basic Audio Implementation (new SDL_Mixer v1):

Stuff needed:
- [x] Add SDL_mixer to project
- [ ] Add music / sound
- [ ] Play music / sound individually
- [ ] Play music & sound together

**Comment by capnkenny** [comment]
@RubyNova as we discussed, seems like these would be the initial requirements for a MVP. Can you think of anything else to be added in the "MVP" phase?

**Comment by RubyNova** [comment]
WAV is not required for MVP as it is windows only.

Can't see anything else that's required at this time.

**Comment by capnkenny** [comment]
Updated so that this reflects current state for audio

**Comment by capnkenny** [comment]
A new revelation based upon how the current audio branch works - currently to have an "event-driven" sequence, the example I have written in `main.cpp` utilizes `SDL_Delay()` which is undesirable as it freezes the main (rendering) thread for NovelRT while allowing audio to continue.

For this, would we want to incorporate an event system? If so, would the Interaction Service be a good starting point for this?
Also, would the above be out of scope of this issue?

**Comment by RubyNova** [comment]
Why is this utilising `SDL_Delay()`?

**Comment by capnkenny** [comment]
Without delaying the thread, the main thread would attempt to run every function immediately (remember, only in `main`, it is not used in the actual service).

**Comment by RubyNova** [comment]
Im not sure i entirely understand. Please post a permalink to the line in question.

**Comment by capnkenny** [comment]
https://github.com/novelrt/NovelRT/blob/8f570910bdf1c3237ea732d66c2b9f6c2b09e7c4/src/main.cpp#L105

**Comment by RubyNova** [comment]
Ok Ive had a read.

You are correct - `SDL_Delay()` is a bad idea here.

What I propose instead is we implement a queueing system somewhere inside the audio service heirarchy. The best way to do this would simply be with an `std::queue<NovelRT::AudioInformation>` where `AudioInformation` is simply a `struct` that is defined like so:
```cpp
struct AudioInformation {
  std::string fileName;
  int playTime;
}
```
From here you can assemble instances of this and add them to the queue (based on your API as per this comment).

You can then simply have the audio*object (wherever you feel the queue should live basically in your heirarchy) also subscribe to `runOnUpdate` and then have a value that updates according to the `deltaMs` and decides when to pop the next file.

**Comment by RubyNova** [comment]
Alternatively we could look at handling this with either multithreading or asynchrony but both sound like a bit much for a v1.0.

**Comment by RubyNova** [comment]
Nit: on reflection this might possibly be HLAPI rather than LLAPI.

**Comment by capnkenny** [comment]
So maybe leave this to discresion of user in LLAPI? Since ultimately I believe an `AudioManager` to make things more streamlined would be a part of HLAPI and could include this

**Comment by RubyNova** [comment]
Yeah what I'm thinking is we can have a `NovelAudioQueue` which accepts a `NovelAudioSource` which can then handle a queue of sounds for that one source.

You could build this into an audio manager type of some description if you prefer, just my 2c.

**Comment by RubyNova** [comment]
To clarify - given the nature of my suggestion it would build on top of the LLAPI directly meaning it definitely would be HLAPI instead.

**Comment by RubyNova** [comment]
We need to update this issue or open a new one as per our discussion on Discord @capnkenny .

**Comment by capnkenny** [comment]
We need to open a new one, as while technically the needs of this _are_ met, we're reworking the API as discussed. I'll close it for now - look forward to DMs being blown up when I'm free so I can get the next issue posted with the right info 👍
