### ISSUE TITLE
Unit tests required for NovelRT::LoggingService.

### ISSUE THREAD

**Issue by RubyNova** [novelrt/NovelRT#142]
As per #141 and the discussion that occured there, tests are probably needed for the logging service.

**Comment by Gnbrkm41** [comment]
👋 I have the test codes ready. However this requires some work on the logger side to make the output readable by the test framework; currently the logger only writes to stdout and it does not seem possible to simply redirect the stdout and read from it. 

Ruby suggested logging to files as well as console so the file can be read instead. However it would be nice if the logging to file can be configurable so it's disabled by default on sample apps.

**Comment by RubyNova** [comment]
Ticket is open again.

**Comment by noobnewbier** [comment]
Let me have a look, I expect to finish this within a week.

**Comment by RubyNova** [comment]
I'm going to rework logging I think. Gonna close this for cleanup's sake.
