### ISSUE TITLE
Rendering Service fails with ES 3.0 Context on AMD/Intel GFX Cards

### ISSUE THREAD

**Issue by capnkenny** [novelrt/NovelRT#146]
Currently, we tell `glad` to load using `gladLoadGLLoader` which causes `glad_glGetUniformBlockIndex` to not be bound and thus an Access Violation exception when using AMD or Intel graphics cards with an ES 3.0 context.

This is inherently due to `glad` currently defaulting to binding the latest GL API, not the latest GLES2/3 API, forcing us to call `gladLoadGLLoader` instead of `gladLoadGLES2Loader`.

@tannergooding confirmed that using the GL ES2 Loader allows Intel and AMD to succeed; I have tested that it is the same for NVIDIA cards as well.

Solutions:
Intel w/ NVIDIA Optimus - #145 
Intel - needs modification to `glad` package in `vcpkg` - microsoft/vcpkg#10098
AMD - needs modification to `glad` package in `vcpkg` - microsoft/vcpkg#10098
NVIDIA - Working as-is

**Comment by RubyNova** [comment]
Was this fixed? I thought you resolved this @capnkenny

**Comment by capnkenny** [comment]
@RubyNova Nope, I only implemented a fix for Optimus.

On that note, I had a proposed solution for `GLAD`'s `vcpkg` port that would fix this as we'd change the generic specification we're given from `vcpkg`, however I haven't touched that branch in a bit and never actually submitted a PR due to the possibility of ditching `vcpkg`. (Also because it would induce a _pretty_ breaking change to anyone pulling `GLAD`)

**Comment by capnkenny** [comment]
This may be resolved - needs re-testing

**Comment by RubyNova** [comment]
I'm taking on this issue as part of the Vulkan support. It shouldn't be too complex to add this (when I have the time).

**Comment by RubyNova** [comment]
We literally don;t use OpenGL ES anymore. Lmao.
