### ISSUE TITLE
.NET Core prints first time welcome message in new CMake toolchain, causing a janky workaround.

### ISSUE THREAD

**Issue by RubyNova** [novelrt/NovelRT#155]
This issue is not something we can fix on our end. The issue is being tracked here: https://github.com/dotnet/sdk/issues/3828

Until this is fixed, we are marking this as `wontfix`.

**Comment by FiniteReality** [comment]
Would probably be better to label 'blocked' instead of 'wontfix'

**Comment by RubyNova** [comment]
Possibly - but I consider `wontfix` to be something *we* "won't fix"....because we can't. 😄

**Comment by FiniteReality** [comment]
This is no longer blocked: https://github.com/dotnet/cli/pull/13275

**Comment by RubyNova** [comment]
Right, but you said you weren't sure when it'd be available for our builds yeah?

We should probably keep this open until its confirmed we have access to the fix.

**Comment by RubyNova** [comment]
Is this resolved now that the ticket were tracking has been closed?

**Comment by FiniteReality** [comment]
It's actually not even an issue anymore; I always run the restore step in cmake configuration stage which bypasses this issue outright.

**Comment by RubyNova** [comment]
OK. Closing.
