### ISSUE TITLE
Clang++9 gives ctad (class argument deduction) warning on GeoVector class

### ISSUE THREAD

**Issue by chrisdevchroma** [novelrt/NovelRT#168]
Compiling Geobounds.cpp included Transform.h with clang++9 gives the following warning (as error) from option -Wctad-maybe-unsupported:
```
NovelRT/include/NovelRT/Transform.h:26:42: error: 'GeoVector' may not intend to support class template argument deduction [-Werror,-Wctad-maybe-unsupported]
      return Maths::GeoBounds(_position, Maths::GeoVector(scale, scale), 0);
                                                                 ^
NovelRT/include/NovelRT/Maths/GeoVector.h:12:9: note: add a deduction guide to suppress this warning
  class GeoVector {
        ^
1 error generated.
```

Solution is to add a deduction guide for the GeoVector templates.
Reference: https://en.cppreference.com/w/cpp/language/class_template_argument_deduction

**Comment by capnkenny** [comment]
@chrisdevchroma @RubyNova 
There's something odd about this - after performing a fresh install of Ubuntu 20.04 and Clang 11, this does not occur and build succeeds as expected. 

If this is the case and other compilers are succeeding without it, should we maybe include a suppression in CMake specifically for Clang 9? Or did we possibly change the warnings to not flag this as an error anymore?

**Comment by RubyNova** [comment]
It sounds to me like Clang 9 may have a bug, but I'll wait for Chris to confirm.

**Comment by chrisdevchroma** [comment]
### Test with various clang versions on Ubuntu 20.04

- [x] 11 - no errors
- [x] 10 - no errors
- [x] 9 - no errors???
- [x] 8 - no errors

**Comment by RubyNova** [comment]
wait...what? On ubuntu 20.0x its fine?

**Comment by chrisdevchroma** [comment]
Yep, same for Fedora 31 with clang 9

**Comment by RubyNova** [comment]
Maybe I should make a new "u wot" label for tickets like this that make no sense.

**Comment by RubyNova** [comment]
@chrisdevchroma what's the state of play with this issue?

**Comment by chrisdevchroma** [comment]
This ticket has been overtaken by time. CentOS 8.4 (which is already EOL) brings clang-12 but without the C++17 filesystem library. At this moment it does not build the current master https://github.com/novelrt/NovelRT/commit/e2775798ff37a0c638e89580bb5f9c1249fa5996
