### ISSUE TITLE
InteractionService does not propagate key state correctly.

### ISSUE THREAD

**Issue by RubyNova** [novelrt/NovelRT#171]
Expected behaviour:
When a key is held down, it should only remain in the `KeyDown` state for a single frame, then transition to `KeyDownHeld`

Actual behaviour:
It never goes past `KeyDown`, so `KeyDownHeld` is never produced as a state.

Steps to reproduce:
1 - set up code to check for `KeyDown` only on a specific key with a log.
2 - attach this code to `Update`.
3 - run the software.
4 - press the key you are checking for.
5 - inspect logs and observe the issue.

**Comment by capnkenny** [comment]
Is this something similar to the issue with polling in the arcade demo?

To clarify, the key would constantly repeat unless we switched over to.... IIRC `GlfwWaitEvents()` instead of `GlfwPollEvents()`

**Comment by RubyNova** [comment]
possibly/probably, im just not looking at it at this moment in time.

If there's already a fix please PR it when you can. 😄

**Comment by capnkenny** [comment]
Oof, the original thought for fixing would not work as it's blocking until input is detected. This will need to be researched to have a proper PR.

**Comment by RubyNova** [comment]
Then we fix the FSM as originally planned. NP

**Comment by RubyNova** [comment]
Update: FSM is actually fine. It's just not updateing keyboard states specifically correctly. Gonna need to investigate further.
