### ISSUE TITLE
Question about NovelRT library api.

### ISSUE THREAD

**Issue by Arkrait** [novelrt/NovelRT#18]
There are a few moments that I would like to resolve before continuing to wrap core api in C. Should we build the library as static or dynamic? And do we only provide C api for consuming or C++ as well?

**Comment by RubyNova** [comment]
This sounds like a design decision best left up to you as it sounds like its mostly dependent on how you wish to set up the SDK.

What I can tell you however is that C++ is a first class citizen for engine usage and that many of our other bindings will be relying on the extern C API.
