### ISSUE TITLE
Improve cross-platform build compatibility and dependency management

### ISSUE THREAD

**Issue by FiniteReality** [novelrt/NovelRT#187]
See #147 for motivation.

This is a reminder to myself that I need to work on it when I feel like shooting myself in the foot with a CMake-sized gun again.

Alternatively, if we want to bite the bullet entirely, I can experiment with some MSBuild based project management, which actually works extremely well with NuGet and .NET Core:

https://github.com/FiniteReality/thermite/blob/master/natives/NativeLibrary.props
https://github.com/FiniteReality/thermite/blob/master/natives/NativeLibrary.targets
https://github.com/FiniteReality/thermite/blob/master/natives/minimp3/minimp3.cxxproj

(In our case, we'd change `<TargetFramework>` to be `Native`, since we're building a native project.)

If we do go the MSBuild route, I can't guarantee full compatibility with Visual Studio (hell, Visual Studio may just croak entirely due to how radically different these projects are from standard vcxproj projects), but we can make the dependencies work more or less just fine. We *may*, however, require custom repos to host our MSBuild-ified versions or just end up absorbing the source in-repo.

**Comment by RubyNova** [comment]
CMake is probably more stable. How you choose to set up CMake is your decision. Whatever makes the most sense and will play ball with whatever dependency management we need to use (I still have no idea how this is gonna proper build on Linux...).

**Comment by RubyNova** [comment]
We did it reddit.

In all seriousness, nice work @FiniteReality - closing this.
