### ISSUE TITLE
OpenAL currently causing Windows builds to fail.

### ISSUE THREAD

**Issue by RubyNova** [novelrt/NovelRT#195]
Title.

Relevant vcpkg issue links:
https://github.com/microsoft/vcpkg/issues/10825

https://github.com/microsoft/vcpkg/issues/9628

We can't do anything about this directly. We'll need to figure out some kind of hack. Marking as `wontfix` until resolved in Vcpkg itself.

**Comment by capnkenny** [comment]
Hey @RubyNova, based on https://github.com/microsoft/vcpkg/issues/12935 I think this can be closed. 
It appears that the issue stems from CMake not choosing proper versioning of the Windows SDK if your OS does not match it, which: 

1. is no longer an issue if you use Win 10 + latest SDK that matches your installed version, and
2. We're moving off of vcpkg in the near future anyways 😄
