### ISSUE TITLE
Option to enable Windowed Borderless Mode (no title bar)

### ISSUE THREAD

**Issue by capnkenny** [novelrt/NovelRT#200]
Currently, whenever we launch the engine's sample, it opens with a title bar when GLFW creates the screen.

For Desktop scenarios, we may have instances where we do not want to do this, and can utilize GLFW's `GLFW_DECORATED` window hint. By setting this to false, we get the following:

![image](https://user-images.githubusercontent.com/10300290/87245952-ca90ca80-c417-11ea-8ba1-08b1a9e5717f.png)

Giving a (if the window size were enlarged) Windowed Borderless option to end users.

With that said, there are certain quirks about it that we'd need to address -
- We cannot resize the screen without making an internal call to glfw/NovelRT to resize the window
- The window cannot be moved around the screen without doing the same above (if I recall correctly)

**Comment by RubyNova** [comment]
> We cannot resize the screen without making an internal call to glfw/NovelRT to resize the window

I think my concern here is how we'd handle it in terms of our API surface. Telling GLFW to resize isn't really a massive deal. Any ideas on how this would affect the API, if at all? Would we need to have some kind of internal interaction rect handling?

> The window cannot be moved around the screen without doing the same above (if I recall correctly)

This one might be a non-issue. Its windows borderless, Its expected that you can't really move it around I'd say?

**Comment by capnkenny** [comment]
> 
> 
> > We cannot resize the screen without making an internal call to glfw/NovelRT to resize the window
> 
> I think my concern here is how we'd handle it in terms of our API surface. Telling GLFW to resize isn't really a massive deal. Any ideas on how this would affect the API, if at all? Would we need to have some kind of internal interaction rect handling?

As per discord, window resizing cannot be handled by the user at all. We would need an API to destroy the current window, and create a new one at a new window size / resolution if we're to offer that to end users.

> > The window cannot be moved around the screen without doing the same above (if I recall correctly)
> 
> This one might be a non-issue. Its windows borderless, Its expected that you can't really move it around I'd say?

Sounds good. We'd most likely want calls to center the window, however, just an FYI :smile:

**Comment by thaumanovic** [comment]
As per discussion with Ruby I'm gonna give this one a shot.

**Comment by thaumanovic** [comment]
As #245 implements this, can we consider this closed? 🦉

**Comment by RubyNova** [comment]
I'm surprised you didn't add any keywords to close this already.

Closing.
