### ISSUE TITLE
Add fullprop alternatives to autoprops?

### ISSUE THREAD

**Issue by RubyNova** [novelrt/NovelRT#215]
Due to a discussion on discord about Sol2's interesting stance on properties, we need a workaround for our ref returning properties. For the short term, @Tylertron1998 is just going to write some helper lambdas to wrap our properties and everything should just kind of work, however I am aware this is not what we agreed on long term.

With that said, the original long term plan _might not make sense_ if Sol2 is the only victim of this - and even if it isn't, the helper lambdas are going to be available via a separate header anyway, so I don't know if we need this anymore.

**Comment by Tylertron1998** [comment]
I think for now the helper lambdas are the best solution - for short *and* long term. Realistically they could also be useful for other languages which don't support ref return property methods; so I think for now we can close this and open it up again if it becomes an issue.
