### ISSUE TITLE
Windows Dependencies need migrating to NovelRT org

### ISSUE THREAD

**Issue by capnkenny** [novelrt/NovelRT#235]
Self titled.

I don't mind hosting the custom vcpkg exports at all for the time being, but we should really probably maintain it through the NovelRT org instead of hosting it on my personal profile.

**Comment by RubyNova** [comment]
You have rights to make new repos. Go for it. 😎

**Comment by capnkenny** [comment]
Lol will do..this is more of a self-reminder though, otherwise I'll forget 😅

**Comment by FiniteReality** [comment]
We should likely make a combined "novelrt build" repo which contains all of the necessary stuff to build docker images for our CI. That should reference a novelrt/vcpkg repo that maintains our custom patches/tweaks to vcpkg for Windows.

**Comment by capnkenny** [comment]
Hahahaha works for me @FiniteReality :smile:

**Comment by RubyNova** [comment]
So...since we're using conan now, is this even relevant anymore?

**Comment by capnkenny** [comment]
@RubyNova if the idea of having a build repo still is relevant, then maybe we can open a new issue to track it. Otherwise, no since the main dependency for this was related to vcpkg.
