### ISSUE TITLE
Make atom factory functions internal

### ISSUE THREAD

**Issue by FiniteReality** [novelrt/NovelRT#249]
We can make our Atom factory functions de-facto internal if we make a single public factory function, which works using template parameters. These template parameters are mostly meaningless, but they allow us to instantiate a unique "flavour" of the function which follows the accessibility of the template parameter itself. If we then make the type name used to access this instantiation private, we can make the factory function de-facto internal, even if the overall definition is public in the Atom type.

The definition would look something like this:
```cpp
template <typename>
int get_id()
{
    static int id = 0;
    
    return id++;
}
```
And to use it, we'd define a type name (it doesn't even have to be complete; just something speakable and referable) in our implementation file(s) and use the function:
```cpp
namespace { // THIS BIT IS NECESSARY!
    class event_id;
}

Atom do_thing_and_get_its_id()
{
    return get_id<event_id>();
}
```
As for the `THIS BIT IS NECESSARY!` comment, that's an unnamed namespace, and it *basically* generates a unique name for the namespace, so that no other implementation file can get the same namespace, even if the symbol gets exported somehow. In C++17, it also gets "internal linkage" which means the symbol(s) don't get exported, meaning nobody else can use them.

The overall effect is that nobody else can have the same `get_id<event_id>();`, unless we explicitly make it so by giving the namespace a non-unique name.

**Comment by RubyNova** [comment]
Question - could we expand on this so that we can directly set the static value for a given type T?
