### ISSUE TITLE
Bison requires from-source build when using Conan.

### ISSUE THREAD

**Issue by RubyNova** [novelrt/NovelRT#266]
As per [this ticket](https://github.com/conan-io/conan-center-index/issues/4443) on the conan centre index due to a bug with `libreadline.so`.

Please note that this issue won't be in effect until #265 is merged. We are also not responsible for resolving this.

**Comment by RubyNova** [comment]
Note to myself: https://github.com/conan-io/conan/issues/8560 related.

**Comment by capnkenny** [comment]
Hey @RubyNova, remind me again - what uses bison on Linux?

**Comment by RubyNova** [comment]
No idea but something needs it or NovelRT throws it's toys out of the pram. Probably libfmt?

**Comment by RubyNova** [comment]
wait hold on - I literally linked it in the ticket, its libreadline which is required by something else, probably libfmt, lol
