### ISSUE TITLE
Remove usages of std::string_view in the LLAPI and engine core.

### ISSUE THREAD

**Issue by RubyNova** [novelrt/NovelRT#29]
I keep running into problems in the engine core of going from a string view to `const char*` for the C-based APIs, specifically OpenGL, FreeType and SDL2.

It's a pain, and uneeded cost, to go from `std::string_view` to `std::string` followed by calling `c_str()`. We could call for the data pointer instead but that's nowhere near as safe as it might not be a null-terminated string in the view.

Thoughts?

**Comment by capnkenny** [comment]
I guess one of the questions I have is - are we getting any performance increase by using `std::string_view' instead of `std::string` at the current moment?

**Comment by RubyNova** [comment]
The only benefit is public immutability which we could probably enforce with `const`.

**Comment by RubyNova** [comment]
It was originally suggested by @Arkrait as it goes, but it's beginning to cause me more problems than it's worth, I can see the benefits but as it stands its just causing extra allocations and constant internal screeching from me every time it happens. Sorry lol.

**Comment by Tylertron1998** [comment]
I agree with the proposed changes - from speaking to @RubyNova in Discord, it seems this is the lesser of few evils.

**Comment by RubyNova** [comment]
Decision reached - in future releases `std::string_view` will not be used in the context of the LLAPI.

**Comment by RubyNova** [comment]
All usages appear to be gone as of #98 . Closing.
