### ISSUE TITLE
Inconcistent spelling with Nrt_catalogue_CreateEntity

### ISSUE THREAD

**Issue by Statharas** [novelrt/NovelRT#293]
https://github.com/novelrt/NovelRT/blob/17758b276b07ce31000a26154b66dd264c7a8b70/src/NovelRT.Interop/Ecs/NrtCatalogue.cpp#L47

Inconsistency with the rest of the calls where `Catalogue` is spelled with a capital C. This carries over to the C# Bindings

**Comment by capnkenny** [comment]
This was resolved with the Audio ECs bootstrap 😀
