### ISSUE TITLE
Refactor NrtRGBAConfigHandle

### ISSUE THREAD

**Issue by jeuxjeux20** [novelrt/NovelRT#318]
Currently, the C interop way of manipulating `RGBAConfig` values is by using the `Nrt_RGBAConfigHandle_*` methods. This is quite uncomfortable to use as it requires a heap-allocated value (`new`/`malloc`) for every new created colour; requires the C API consumer to use the `getR` ,`getB`, etc. methods for accessing each value; and is finally source of confusion, see #315 and #317.  

Because this is a relatively simple value, the `NrtRGBAConfigHandle` can probably be converted to a C struct.

**Comment by RubyNova** [comment]
Please note - the type is now called NrtRGBAColourHandle.

**Comment by SmylEFace** [comment]
I can take this one
