### ISSUE TITLE
Split `NovelRT::Ink` off to be compiled conditionally (Temporarily)

### ISSUE THREAD

**Issue by capnkenny** [novelrt/NovelRT#319]
As part of the SDK work, we will need to ensure that Ink is conditional as people using pure C++ will not necessarily need to rely and/or want to include Ink, which forces a `dotnet` dependency on end users.

For now, until we refactor the Engine to have as part of language bindings, we'll use a conditional define to include parts of the Ink codebase (including a `conan` option to by default include it)

**Comment by capnkenny** [comment]
@RubyNova can you confirm that this is in line with what we had spoken about? I'm down for any changes - for reference, I'm looking at what was pinned on #development.

**Comment by RubyNova** [comment]
Seems about right. :)
