### ISSUE TITLE
VS Task is broken

### ISSUE THREAD

**Issue by capnkenny** [novelrt/NovelRT#328]
Self-titled. 
When attempting to find the VS Task, it references the no-longer-existing `conanfile.txt` instead of `conanfile.py` and cannot be used for installing the Conan dependencies inside of VS 2019.

**Comment by RubyNova** [comment]
Do we have confirmation this is actually broken?

**Comment by capnkenny** [comment]
I took a brief amout of time today to find this out - yes, this is broken. Since `conanfile.txt` no longer exists, the task is no longer able to be used.

**Comment by RubyNova** [comment]
This is resolved in #332
