### ISSUE TITLE
Implement clang-format stylesheet.

### ISSUE THREAD

**Issue by RubyNova** [novelrt/NovelRT#35]
We need to get up and running on `clang-format` based on our current code style. Some stuff keeps passing in PRs when it shouldn't and really it'd be great to automate this with `clang-format`.

**Comment by jatin69** [comment]
Hey @RubyNova 
I use [this clang-format file](https://github.com/jatin69/FTP/blob/master/.clang-format) in my c++ projects. Kindly review this file and associated codebase formatting, and let me know if this one works for you. I'll send a PR to add the file.

**Comment by RubyNova** [comment]
Thanks, I'll check it out.

**Comment by capnkenny** [comment]
Picking this up next as formatting is currently hellish 🗡️ 

Based on Microsoft (.NET) formatting with a few tweaks as we go
-Option to run formatter via CMake
-Option to check formatting via CI (which will fail the build if anything is found)
