### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by RubyNova** [novelrt/NovelRT#359]
As per the discussion in #248 we need to add a CONTRIBUTING.md to make this repository friendlier to newcomers. :)

**Comment by theballmarcus** [comment]
I dropped a PR - I am fairly new to GitHub, so I'm not sure if I should write it here or not :)

**Comment by RubyNova** [comment]
Hi there @theballmarcus - thanks! It's late here in the UK, so I'll wait for one of the US maintainers look at it while I'm asleep, I'm sure they'll be happy to give pointers and feedback. Thank you for contributing!

**Comment by theballmarcus** [comment]
Thank you so much!

**Comment by RubyNova** [comment]
Ticket is open again since the last person ghosted us.

**Comment by capnkenny** [comment]
Too late for hacktoberfest, but as discussed previously in Discord, I'll pick this up.
