### ISSUE TITLE
Re-organise Maths headers.

### ISSUE THREAD

**Issue by RubyNova** [novelrt/NovelRT#361]
The Maths headers (under include/NovelRT/Maths) are currently all self-contained. As per the new design philosophy, individual types should no longer be able to be included directly, but rather they should only be accessed via NovelRT.h or via their respective "namespace header", so Maths.h in this case. This also means moving all forward declarations and includes to this namespace header along with adding their respective preprocessor include guards and errors. You can see a good example of this implementation at include/NovelRT/Ecs/Ecs.h and the individual type headers.

**Comment by anindyasen** [comment]
Hello, I am participating in hacktoberfest, Can I work on this issue as a part of it?
thank you

**Comment by RubyNova** [comment]
Hi there @anindyasen - sure, sorry for not seeing this earlier. I'll assign it to you. :)

**Comment by RubyNova** [comment]
Hi there @anindyasen - have you abandoned this?

**Comment by RubyNova** [comment]
Assuming ticket has been abandoned. Reopening.
