### ISSUE TITLE
Maths namespace has incomplete doxygen documentation in its headers.

### ISSUE THREAD

**Issue by RubyNova** [novelrt/NovelRT#362]
This one is pretty much what it says on the tin - the Maths namespace is lacking complete doxygen-based documentation in it's headers, especially when compared to a namespace such as ECS. Adding doxygen comments of similar caliber to the Maths headers will resolve this issue.

**Comment by LinuxLegend** [comment]
Taking on this one, thank you for setting up issue!

**Comment by RubyNova** [comment]
Assigned. :)

**Comment by LinuxLegend** [comment]
(For future issue to work on: Split up intersectsWith into intersectsWithAABB (for evaluating non-rotated bounding boxes) and intersectsWIth (for evaluating rotated bounding boxes)

**Comment by Pheubel** [comment]
I think i am up for the task
