### ISSUE TITLE
Integrate Fabulist into NovelRT

### ISSUE THREAD

**Issue by FiniteReality** [novelrt/NovelRT#394]
After #383 we're currently stuck without any form of interface for non-programmers. We should implement [Fabulist](https://github.com/NovelRT/Fabulist), our new VN language into NovelRT.

The idea is roughly:
- Fabulist is used to write VN contents
- Something else is used to store data for animations/scenes/etc (maybe Lua based too?)
- Something *else* is used to manage save states and such. (Fabulist will have a serializable "state" payload which represents the current state in the story, including things like variables)

**Comment by RubyNova** [comment]
I'm doing the basic integration, but once imgui is in this will still primarily be on @FiniteReality to ensure she's happy with the APIs etc.
