### ISSUE TITLE
Resizing or minimizing/maximizing window causes crash

### ISSUE THREAD

**Issue by thaumanovic** [novelrt/NovelRT#401]
Messing around with the InputEcsSample project; it seems resizing the window in any way (dragging, minimizing, maximizing) causes the engine to crash.

Debugging causes the app to break here:
https://github.com/novelrt/NovelRT/blob/267af6543c2590d7e1e81c5df83b167bdd6c934b/src/NovelRT/Graphics/Vulkan/VulkanGraphicsDevice.cpp#L500

**Comment by thaumanovic** [comment]
Call stack:

`<unknown> 0x00007fff4e86dd7e
<unknown> 0x00007fff4e86d499
<unknown> 0x00007fff3e1f1aab
<unknown> 0x00007fff3e1f2317
<unknown> 0x00007fff3e1f4119
<unknown> 0x00007fff50c482ff
<unknown> 0x00007fff50bd5a0a
<unknown> 0x00007fff50c4730e
<unknown> 0x00007fff4e4b466c
<unknown> 0x00007fff3b7864c0
NovelRT::Graphics::Vulkan::VulkanGraphicsDevice::PresentFrame() VulkanGraphicsDevice.cpp:500
NovelRT::Ecs::Graphics::DefaultRenderingSystem::Update(Timestamp, Catalogue) DefaultRenderingSystem.cpp:335
<lambda_878adfa4...>::operator()<…>(Timestamp, Catalogue) SystemScheduler.cpp:86
std::invoke<…>(<lambda_878adfa4...> &, NovelRT::Timing::Timestamp &&, NovelRT::Ecs::Catalogue &&) type_traits:1488
std::_Invoker_ret::_Call<…>(<lambda_878adfa4...> &, NovelRT::Timing::Timestamp &&, NovelRT::Ecs::Catalogue &&) functional:651
std::_Func_impl_no_alloc::_Do_call(NovelRT::Timing::Timestamp &&, NovelRT::Ecs::Catalogue &&) functional:822
std::_Func_class::operator()(Timestamp, Catalogue) functional:869
NovelRT::Ecs::SystemScheduler::CycleForJob(unsigned long long) SystemScheduler.cpp:114
<lambda_acc57394...>::operator()() SystemScheduler.cpp:172
std::invoke<…>(<lambda_acc57394...> &&) type_traits:1478
std::thread::_Invoke<…>(void *) thread:55
<unknown> 0x00007fff4e816c0c
<unknown> 0x00007fff4f2954e0
<unknown> 0x00007fff50ba485b`

**Comment by RubyNova** [comment]
I think that's happening here is that the resize doesn't destroy the swapchain in time because the rendering system might be building command lists on another thread, but it is doing the correct logic otherwise. I'll need to figure out how to fix that.
