### ISSUE TITLE
Update the logic in StepTimer to account for scenarios where _frequency > TicksPerSecond

### ISSUE THREAD

**Issue by tannergooding** [novelrt/NovelRT#41]
As called out on https://github.com/novelrt/NovelRT/pull/34#discussion_r323548711, the StepTimer can technically bug out if the hardware timer frequency is greater than the TicksPerSecond.

This is problematic because the math is using integer arithmetic and follows `(counterDelta * TicksPerSecond) / _frequency`, so if `_frequency > TicksPerSecond` you can end up getting "zero" as the tick delta.

A solution should be devised that takes this into account so that users still get the appropriate updates.

**Comment by Pheubel** [comment]
i'll try to have a look at it

**Comment by RubyNova** [comment]
GLHF
