### ISSUE TITLE
Create Pull Request and Issue Templates

### ISSUE THREAD

**Issue by capnkenny** [novelrt/NovelRT#426]
As part of the discussion on #384, we'll want to add pull request templates and issue templates.
This will do the following for us:

- Allows us to become more uniform in quality with open Issues / Pull Requests
- Allows us to better provide examples to the community on what we expect when opening an Issue / Pull Request
- Allows us to define what _is_ versus _is not_ allowed to have a Pull Request without an existing Issue opened (looking mainly at code/functionality changes versus just a documentation change)

**Comment by RubyNova** [comment]
why is this still open?
