### ISSUE TITLE
Remove needless const declarations.

### ISSUE THREAD

**Issue by RubyNova** [novelrt/NovelRT#44]
As per a previous discussion with @tannergooding , the code style is being modified to not use the `const` modifier in places where pointers and references are not being used. Its a simple task however we have it in many locations right now, so may take a little while to actually fully do.

**Comment by RubyNova** [comment]
An approach I think we should take to this is just changing these redundant modifiers as we go rather than doing it all in a single PR.

**Comment by jatin69** [comment]
Hey, @RubyNova I would like to take this on. Can you please elaborate what needs to be done, and the starting point, which file should I edit first.

**Comment by RubyNova** [comment]
Hey @jatin69 , so to clarify this a little for you:

When I first began writing this codebase, I had no idea what I was doing with C++ and got a tad overzealous with `const` correctness. As a result, the codebase has a few instances where methods were defined as such:

```cpp
void someMethod(const int someParameter)
```

Naturally, the `const` modifier being applied to the parameter here makes no sense as we are passing it in by value. We don't actually care if that parameter is modified or not as it doesn't affect anything externally anyway. This is _not_ to be confused with marking methods as `const`, like so:

```cpp
void someMethod() const;
```

This snippet is perfectly fine as it is being used to indicate calling the method will not mutate the object in question - it is effectively a different use case, and should be left alone.

As for where to start...well if I remember correctly this issue is kind of spread across all the source files currently in `master`, so you could branch off from there and investigate. If you want to follow our branch naming scheme, a good name for your branch might be `misc/const-correctness-cleanup` as an example.

If you have any further questions feel free to ask! :smiley:

**Comment by jatin69** [comment]
@RubyNova alright. I'll start the investigation. I'll first update a few files and get them reviewed before moving on to all files.

**Comment by jatin69** [comment]
@RubyNova 
Should function pointers be const? I think they should be. This will explicitly tell that the pointer value will not change.

**Comment by RubyNova** [comment]
Could you clarify which function pointer(s) you are referring to?

**Comment by jatin69** [comment]
In file `NovelBasicInteractionRect.cpp`,
`const std::function<void(NovelInteractionObject*)> notifyHasBeenDrawnObject`

This should remain `const` in my opinion. What do you think?

**Comment by RubyNova** [comment]
I remember having problems with attempting that. I'm unsure if said problems are still around, but I think this is going to be a case of "try it and see" because it's been a while since I was in that part of the codebase, but if it could be `const` then it would be nicer for sure.

**Comment by jatin69** [comment]
Also, These should not be const I think. `const` here does not imply anything useful. Thoughts?
```cpp
NovelLayeringService::~NovelLayeringService() {
  for (const auto& value : _layerMatrix) {
    for (const auto& renderObj : value.second) {
      delete renderObj;
    }
  }
}
```

**Comment by RubyNova** [comment]
That's more just futureproofing after multiple discussions. There's talks of reworking this to rely on smart pointers and such anyway, so I wouldn't bother modifying that specific snippet, personally.
