### ISSUE TITLE
Adjust the way include paths are handled so it uses the project directory and not the CMake source directory.

### ISSUE THREAD

**Issue by RubyNova** [novelrt/NovelRT#448]
This should be a very low cost fix with good robustness benefit.

The goal here is to simply replace `CMAKE_SOURCE_DIR` with `PROJECT_SOURCE_DIR` and still have CMake work correctly.

This change should allow people to use the NovelRT Engine via `FetchContent` functionality.

**Comment by bjauny** [comment]
I'll check this!

**Comment by RubyNova** [comment]
Awesome, let us know if you need anything

**Comment by bjauny** [comment]
Running the steps of the README on a  Linux Mint install I cannot build the project. I attach the error logs. Did I miss something?
[err.log](https://github.com/novelrt/NovelRT/files/9742267/err.log)

**Comment by RubyNova** [comment]
You have - but no worries I got you. :)

Our readme states we do not work with GCC at this time and it's due to the exact error about type punning you are getting.

If you can, please use clang or MSVC instead.

**Comment by bjauny** [comment]
Oh, I missed this! I got it, I'll try again, thanks for the quick feedback.
