### ISSUE TITLE
Test install targets for NovelRT

### ISSUE THREAD

**Issue by RubyNova** [novelrt/NovelRT#455]
Given our move to FetchContent-driven dependencies we need to make sure installed copies of the engine still work.

**Comment by capnkenny** [comment]
I'll take this since the SDK is dependent on it.

**Comment by capnkenny** [comment]
Based on what we currently have, it appears that although we can install, our installation is becoming slightly... fragmented? Basically if we include `NovelRT.cmake`, we need to make sure that all the other deps being referenced are being found and included, even though we're already providing them (so we need to include the other installed files like `fabulist.cmake`, `ZLIB.cmake`, etc).

@FiniteReality - any suggestions here? Or do you believe this is par for the course?
(The idea here was that if not building by source, we could provide the dependencies to link against + respective headers)
