### ISSUE TITLE
Vulkan-Loader should support building Wayland support if detected

### ISSUE THREAD

**Issue by capnkenny** [novelrt/NovelRT#478]
Atm, if the Vulkan dependencies are vended by NovelRT, by default we will turn off Wayland support as not having Wayland will force Linux users to fail at the CMake level. (An example is a WSLg instance w/o Wayland support)

We should add a check to see if Wayland is found, and if so we'll want to turn the `BUILD_WSI_WAYLAND_SUPPORT` flag back on.

**Comment by RubyNova** [comment]
This bug itself is something I have questions about.

Like.

If you're on an X11 machine and want to publish a game to a Wayland one, what happens?

**Comment by RubyNova** [comment]
Okay - in that case we should definitely note that if users want to deploy to other machines, that they use the SDK, and then we figure out how to make that work later

**Comment by capnkenny** [comment]
We _can_, if desired, force users to only use the SDK instead of vendoring? Just putting the option out there

**Comment by RubyNova** [comment]
No I don't think that's required unless we want to give Linux special behaviour here. On other platforms its a non-issue and so we should just probably make sure we can support building for Wayland with some kind of detection, but note it in our docs that if you want to deploy to Wayland from X11 you can't do it this way. Its easier and keeps the behaviour more in-line.

**Comment by RubyNova** [comment]
We're not doing this anymore due to a change in the fact we are no longer self-scaffolding Vulkan. This will be removed in the future.
