### ISSUE TITLE
NovelRT C API deleter methods are inconsistently named.

### ISSUE THREAD

**Issue by RubyNova** [novelrt/NovelRT#513]
**_Note: for support questions, please use the #engine-user-help channel in our [Discord](https://discord.novelrt.dev/) or [create a discussion](https://github.com/novelrt/NovelRT/discussions/new). This repository's issues are reserved for feature requests and bug reports._**

**Describe the issue:**
There is a naming inconsistency in the C API where some of the deleter methods are tagged as `Delete` and some as `Destroy`.

**Please provide the steps to reproduce if possible:**
1. Clone the repo
2. Inspect the interop header files
3. Observe the issue

**Expected behaviour:**
 I believe the intended naming convention is `Destroy`.

**Please tell us about your environment:**  
N/A

**Additional context:**
This doesn't functionally break anything, its just gross to read.

**Comment by Sakshi-75** [comment]
Hi @RubyNova , Can I work on this?

**Comment by RubyNova** [comment]
@Sakshi-75 Sure. Assigned.
