### ISSUE TITLE
Doxygen generation appears to be wrong for some definitions.

### ISSUE THREAD

**Issue by RubyNova** [novelrt/NovelRT#552]
**_Note: for support questions, please use the #engine-user-help channel in our [Discord](https://discord.novelrt.dev/) or [create a discussion](https://github.com/novelrt/NovelRT/discussions/new). This repository's issues are reserved for feature requests and bug reports._**

**Describe the issue:**
The documentation contains Doxygen generation tags.

**Please provide the steps to reproduce if possible:**
1. Open the documentation at https://novelrt.github.io/NovelRT/annotated.html

**Expected behaviour:**
The documentation should not contain Doxygen generation tags.

**Please tell us about your environment:**  
  - Engine Version: N/A
  - Configuration: N/A
  - OS Version: N/A
  _If building from source_:
  - Compiler Version: N/A
  - Git fork/branch URL: main

**Additional context:**
Witness my pain
![image](https://user-images.githubusercontent.com/25829582/214334483-3fc288e4-77b9-4e97-8d8f-58cd91b26636.png)

In order to fix this, someone just needs to fix the offending comments in the code. It should be very simple to locate and fix.

**Comment by Alftron** [comment]
Hello, I created PR #553 before requesting the issue to be assigned to me. Could this issue be assigned to me if possible, please?

**Comment by RubyNova** [comment]
Sorted.

**Comment by Alftron** [comment]
Thanks PR #553 should be ready and has been updated to the required standards. Thank you

**Comment by Alftron** [comment]
Thank you. I've updated the PR to follow the template, apologies for that.
