### ISSUE TITLE
Getting an error during the building process

### ISSUE THREAD

**Issue by MichaelPCameron** [novelrt/NovelRT#567]
during the building process i am running into an error in CopyRuntimeDependencies.cmake file at line 18 and 85 getting this error:
    $<TARGET_RUNTIME_DLLS:UIEventExample>

  Expression did not evaluate to a known generator expression

**Comment by RubyNova** [comment]
Hey there, I appreciate the bug report - however without more information this is going to be hard to fix. Can you fill out the bug report template form with the appropriate information so I can begin taking a look? Thanks.

**Comment by MichaelPCameron** [comment]
**_Note: for support questions, please use the #engine-user-help channel in our [Discord](https://discord.novelrt.dev/) or [create a discussion](https://github.com/novelrt/NovelRT/discussions/new). This repository's issues are reserved for feature requests and bug reports._**

**Describe the issue:**
A clear and concise description of what the the current behaviour is.


**Please provide the steps to reproduce if possible:**
1. Clone the repo
2. setup files w/ the command prompt using CMake
3. went over to visual studio and changed the installer root and the build root to what was provided
4. calibrated
5. See error
          - 16 errors at line 85 and 16 errors at line 18 saying that the expression did not evaluate known generator expression
          - having trouble with the target line


**Expected behaviour:**
I expected for the build to finish and able to load up and check out the project


**Please tell us about your environment:**  
  - Engine Version: [v1.00]
  - Configuration: [Release ]
  - OS Version: [Windows 10 Version 10.0.19044
  _If building from source_:
  - Compiler Version: [ Visual Studio 2019 v16.11.24 ]
  - Git fork/branch URL:


**Additional context:**
Add any other context about the problem here.

**Comment by RubyNova** [comment]
What version of CMake is this using? I think VS2019 might be shipping with a CMake version that's too old, and will require changing the settings. IIRC, we currently require CMake 3.21. It currently passes in our VS2019 CI, so I'm hoping it's just this.

**Comment by MichaelPCameron** [comment]
i have cmake 3.26

**Comment by RubyNova** [comment]
Is VS2019 currently using it? By default it won't.

**Comment by MichaelPCameron** [comment]
thats probably the problem what is the best way to change the default, thank you for helping me btw!

**Comment by RubyNova** [comment]
I believe it should be in your CMakeSettings.json, I forget precisely where as I mostly use VSCode and Neovim these days, but the value in the CMakeSettings.json that needs change is `cmakeExecutable` - I think VS2019 should have some UI to tweak this easier than typing raw strings though. It might be under the advanced CMake settings? Unsure.

**Comment by MichaelPCameron** [comment]
i switched over to 2022 and there isnt any errors but how do i run the program?

**Comment by MichaelPCameron** [comment]
i have the engine working now how do i utilize it?

**Comment by Pheubel** [comment]
Right now, the best place to look at are the sample applications. They show you how to set up an executable that makes use of the engine in various ways. 

But i think the problem for this issue has been resolved.

**Comment by RubyNova** [comment]
LGTM, closing.
