### ISSUE TITLE
SDL2-Mixer external support broken

### ISSUE THREAD

**Issue by capnkenny** [novelrt/NovelRT#58]
Due to (what seems to be) the newest update to the SDL2-mixer vcpkg files, adding in any modules for SDL2-Mixer besides core is broken on Windows. This is due to the bug resolving to `.lib` for every module which does not play nicely (i.e. using Vorbisfile results in a 0xc000012f error as it links to the library via `.lib` instead of `.dll`)

Until this is resolved, we can only support whatever formats SDL2 Mixer supports OOB.

For reference:
https://github.com/microsoft/vcpkg/issues/8429

**Comment by RubyNova** [comment]
To clarify - no additional work should be done on this front for now, just provide a complete audio package with whatever audio files SDL2 Mixer support OOTB.

We will add support for other audio files once this is resolved.

**Comment by capnkenny** [comment]
This has been resolved as per the referenced vcpkg issue. Closing.
