### ISSUE TITLE
should add CI

### ISSUE THREAD

**Issue by jatin69** [novelrt/NovelRT#66]
This project seems to have a lot of active changes and PRs. It makes sense to add a Continous Integration to the codebase to verify that PRs aren't breaking anything.

**Comment by jatin69** [comment]
If you let me know the compile statements and requirements, I'm up to add a GitHub actions CI workflow.

**Comment by RubyNova** [comment]
@tannergooding is already helping me with a public Azure DevOps pipeline (it's still a WIP, I've been a busy human being).

I'll add this to our TODOs, so we actually remember to finish this.

**Comment by tannergooding** [comment]
The branch adding the basic build scripts is here: https://github.com/tannergooding/NovelRT/tree/build-scripts

Just need to finish adding the cmake/vcpkg support, etc and they should be done.

**Comment by RubyNova** [comment]
Sweet good to hear.

**Comment by RubyNova** [comment]
As per #67 the build scripts are in place. We just need to set up the appropriate things on AzDO and it's good to go.

**Comment by RubyNova** [comment]
CI is now integrated. Closing.
