### ISSUE TITLE
Implement Timestamp type

### ISSUE THREAD

**Issue by capnkenny** [novelrt/NovelRT#70]
As discussed on Discord, a basic implementation would look like this:

* You track a scene graph
* Interactions can trigger events
* External services (like a timer) can trigger events

This would be part of a central eventing API, as well as to avoid scenarios as below -

_As referenced in the basic audio PR:_

There is a subtle, but non obvious bug here that deals with floating-point values and timestamps in general. Namely around `Frequency` being significantly larger than the `TicksPerSecond`, which you've defined to be `1000`. For example, on my box, `Frequency` is `10'000'000`, which means that this has a risk of producing a really tiny result and incurring rounding error.

_Originally posted by @tannergooding in https://github.com/novelrt/NovelRT/pull/33_

**Comment by RubyNova** [comment]
I'm unsure the description lines up with the title here so I'm not 100% sure this ticket is what I think it is but certain enough to assume this is related to `NovelRT::Timing::Timestamp` which has now been implemented.

Closing.
