### ISSUE TITLE
Add helper for failure reponses from methods

### ISSUE THREAD

**Issue by capnkenny** [novelrt/NovelRT#71]
Currently, we are checking against constants or magic numbers, especially when dealing with SDL-based calls. These should get wrapped in a helper method so that if they fail, we can handle them appropriately with logging.

_As referenced in basic audio PR:_

`SDL_SUCCESS` in particular seems like something that could be solved by a helper method. Namely something like `ThrowIfFailed(MyFunc(args), "Error Message")`

This would then check for success, log the error, and throw an exception.

_Originally posted by @tannergooding in https://github.com/novelrt/NovelRT/pull/33_

**Comment by capnkenny** [comment]
Would benefit from #24

**Comment by mastorm** [comment]
Will take care of this

**Comment by RubyNova** [comment]
Assigned. Good luck!
