### ISSUE TITLE
Configure Doxygen for CI/CD on AzDO.

### ISSUE THREAD

**Issue by RubyNova** [novelrt/NovelRT#76]
As per the most recent PR (#75 ) for our CI/CD pipeline, Doxygen isn't actually working when used in our CI/CD setup currently.

We need to figure out how we get this functional and then figure out how to package it up SDK in the future.

**Comment by capnkenny** [comment]
No longer using AzDO - @FiniteReality do we know if Doxygen is working in GH Actions at all?

**Comment by FiniteReality** [comment]
It should work, I think? IIRC the docker image has the correct doxygen version installed

**Comment by capnkenny** [comment]
Yeah, I just confirmed in the Ubuntu runs (ty!) - it generates each time. Closing as once we're ready for SDK documentation we can approach packaging then.
