### ISSUE TITLE
[Proposal] renaming Novel* types without the prefix and using namespaces for engine related types.

### ISSUE THREAD

**Issue by Tylertron1998** [novelrt/NovelRT#78]
Currently, we have a lot of types prefixed with `Novel`; see: NovelObject.cpp, NovelRenderingService.cpp, etc.

We use this to describe the fact that the type is core to the engine - but we could use namespaces instead.

This comes with some design considerations. What do we do for commonly named types, e.g. `NovelObject` - `Object` itself would be way too generic. Do we try to be consistent with all naming and just remove the prefix no matter the ambiguity? Do we do this selectively, considering if the type name would be descriptive enough without the prefix?

**Comment by RubyNova** [comment]
Well, `NovelObject` no longer exists with that name as per #73 . It is now simply called `NovelSurfaceObject` instead.

That aside, what would you prefer to do?

**Comment by Tylertron1998** [comment]
WorldObject is not too generic of a name, IMO - are there any other types that could be of concern?

**Comment by RubyNova** [comment]
Not off the top of my head, but regardless, what is your proposed replacement? Just namespaces?

**Comment by Tylertron1998** [comment]
In my mind - namespaces are used to describe a types "belonging" - so the namespace `NovelRT` should tell the end user that "hey this type is for NovelRT" - for very core and engine only things, we could even affix a `core` to the namespace, so:
```cpp
namespace NovelRT::Core
{
class NovelWorldObject {}
}
```

**Comment by RubyNova** [comment]
Resolved as of #98 . Closing.
