### ISSUE TITLE
Move common rect arguments to a struct.

### ISSUE THREAD

**Issue by RubyNova** [novelrt/NovelRT#8]
**Where we're at right now**

As it stands, the arguments the rendering service takes to create rects are a little...long. It makes maintenance a little cumbersome.

As an example, currently to instantiate an image rect the constructor looks like:
```
    NovelImageRect::NovelImageRect(NovelRenderingService* novelRenderer, const float screenScale, const GeoVector<float> &position, const std::string_view imageDir,
                                   const float rotation, const GeoVector<float>& scale, const int layer, const int orderInLayer)
```

but with a struct, this could be reduced to

```
NovelImageRect::NovelImageRect(NovelCommonArgs, std::string_view imageDir)
```

Opinions?

**Comment by Arkrait** [comment]
yup, was thinking about proposing this for quite some time because such a long argument lists really hurt readability

**Comment by RubyNova** [comment]
It would also allow for some things to become optional, which we really need.
