### ISSUE TITLE
Refactor NovelRunner into Dispatcher/Application Model

### ISSUE THREAD

**Issue by capnkenny** [novelrt/NovelRT#87]
In order to set up multi-threading as well as making it easier to develop future services, we should break `NovelRunner` apart, allowing NovelRT to have the following setup:

> -- Application (Singleton, Exposes Services)
> -- Various Services
> -- Dispatcher (Per Thread, Runs the Event Pump)

Currently, `NovelRunner` does both of what the "Application" and the "Dispatcher" would do, and is not currently a singleton. This can pose many problems, as theoretically end users can create as many runners as they want, which would multiply the number of services per runner.

The suggested method of doing this, as per @tannergooding's comments in Discord, would be to:
> * Rename Runner to Application
>   * It exposes a static getCurrent() method so anyone can retrieve services, etc
> * Break out the event loop logic into some kind of Dispatcher (or Runner) class
>   * This allows you to queue/dispatch pending events
>   * This is "per thread" and are created lazily

This would be a larger refactoring job, and may need to wait until other PRs are merged (logging, UBO, etc).

**Comment by RubyNova** [comment]
Since we've agreed to go full DOD, Application/Dispatcher will probably won't work as well. Instead, we probably want to look into a job system or something similar.

**Comment by RubyNova** [comment]
This will be addressed in an upcoming PR.
