### ISSUE TITLE
Introduce built-in camera modes for NovelRT::Graphics::Camera?

### ISSUE THREAD

**Issue by RubyNova** [novelrt/NovelRT#91]
As per #73 I have introduced the groundwork for supporting multiple camera view/projection view types.

Its a bit messy and needs cleaning up, but once its done we can look into this in further detail for Novel3D probably, I can't see them getting too much use out of it in the current state of the engine.

We can either remove it or try to implement it however I'm a bit "on the fence" about it, and would like other people's opinions.

**Comment by RubyNova** [comment]
Semi-implemented as of #98 . Approved after discussion with the approach of static factory methods as opposed to an enum.

**Comment by RubyNova** [comment]
I'm opening this issue up as something someone else can pick up, as the second half of this particular feature is not required for the base 2D API surface.

Basically, we need a perspective camera factory method in a similar vein to that of our default orthographic camera factory method, i.e. `std::unique_ptr<Camera> Camera::createDefaultOrthographicProjection(const Maths::GeoVector2<float>& windowSize)`. except it would be called `createPerspectiveProjection` instead of `createDefaultOrthographicProjection`.

**Comment by Shidesu** [comment]
I guess I'll try that one
The ~~wrong~~ Kao.
