### ISSUE TITLE
Window size does not auto-adjust to 3840 x 1080 correctly

### ISSUE THREAD

**Issue by Banananaman91** [novelrt/NovelRT#96]
When the engine starts, window size auto-adjusts to main screen size whilst not adjusting correctly to the resolution.

Expected to correctly display at screen resolution or Window size to be limited to display resolution.

Window size adjusts to 32:9 aspect ratio without the display adjusting to 3840 x 1080 resolution.

To reproduce, run project on 32:9 monitor at 3840 x 1080 resolution. Testing on other monitor resolutions advised.

![NovelRTBug](https://user-images.githubusercontent.com/43844902/71186616-705ecb00-2275-11ea-8b23-c3f2008ccf95.jpg)

**Comment by RubyNova** [comment]
This will be resolved by #376 as the view projection has been handled correctly in the new Vulkan pipeline.
