### ISSUE TITLE
Glad should be bundled with the project instead of being pulled from vcpkg

### ISSUE THREAD

**Issue by Nihlus** [novelrt/NovelRT#99]
At the moment, NovelRT utilizes Glad as a rendering layer and function loader, allowing it to access various OpenGL extensions and profiles in a unified manner.

However, Glad is being imported via vcpkg, which is orthogonal to the way Glad is designed to be used. By design, Glad generates a single source file and two header files, which are intended to be directly included in projects utilizing it. The files are generated to fit the needs of the project, in terms of which Khronos specification it uses, the version of the specification, the extensions it would like to have available, etc. 

This presents itself as an issue in the following ways:
* NovelRT does not have control over what OpenGL API it accesses, and is constrained to the one selected by the packager of Glad in vcpkg
* NovelRT cannot be built without the use of vcpkg, since, by design, no distribution of Linux, Windows, or Mac has a system-level package available for Glad

Fixing this issue by directly generating and including Glad in NovelRT would allow building the project without the use of vcpkg, and let NovelRT define exactly which extensions and what OpenGL version it requires.

See the following links for information about Glad, and its intended use.
* [Khronos Wiki - Glad][1]
* [Glad's web-based API generator][2]
* [learnopengl - Getting Started, explaining Glad][2]

[1]: https://www.khronos.org/opengl/wiki/OpenGL_Loading_Library#glad_.28Multi-Language_GL.2FGLES.2FEGL.2FGLX.2FWGL_Loader-Generator.29
[2]: https://glad.dav1d.de/
[3]: https://learnopengl.com/Getting-started/Creating-a-window

**Comment by RubyNova** [comment]
This is currently being handled by @FiniteReality in #196 . The rewrite currently generates the glad files whenever a fresh build is done.

**Comment by FiniteReality** [comment]
FWIW, GLAD is definitely available in system-level packages: https://packages.debian.org/buster/python3-glad (This is what I'm using on my Linux install, for example)
However, it should probably be installed using pip: `python3 -m pip install glad`

**Comment by RubyNova** [comment]
Absolutely. `pip` is the correct solution for this.

**Comment by RubyNova** [comment]
Resolved. closing.
